# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'engine/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(456, 181)
        Settings.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(290, 20, 150, 30))
        self.back.setMaximumSize(QtCore.QSize(150, 30))
        self.back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.back.setStyleSheet("")
        self.back.setObjectName("back")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 241, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autorun = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.autorun.setStyleSheet("")
        self.autorun.setObjectName("autorun")
        self.verticalLayout.addWidget(self.autorun)
        self.hide_mod = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.hide_mod.setStyleSheet("")
        self.hide_mod.setObjectName("hide_mod")
        self.verticalLayout.addWidget(self.hide_mod)
        self.protect = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.protect.setStyleSheet("")
        self.protect.setObjectName("protect")
        self.verticalLayout.addWidget(self.protect)
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.back.setText(_translate("Settings", "Назад"))
        self.autorun.setText(_translate("Settings", "Автозагрузка"))
        self.hide_mod.setText(_translate("Settings", "Скрытый режим"))
        self.protect.setText(_translate("Settings", "Защитить Бота"))
